name: Docker Build & Push

on:
  push:
    branches:
      - main  # أو الفرع اللي تريد تنفذ عليه

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout الكود
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. تسجيل الدخول للـ Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker Image
      - name: Build Docker Image
        run: docker build -t thesaud/grok30-api:latest .

      # 4. Push Docker Image
      - name: Push Docker Image
        run: docker push thesaud/grok30-api:latest
